from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Literal

from pydantic import (
    BaseModel,
    Field,
    ValidationError,
    field_validator,
)

from config import (
    CHUNKS_FILE,
    EVIDENCE_FILE,
    STATE_FILE,
)
from local_llm import GenConfig, LLM


STATE_VERSION = 3

EXTRACTION_MAX_NEW_TOKENS = 2048
EXTRACTION_TEMPERATURE = 0.0
EXTRACTION_TOP_P = 1.0
EXTRACTION_RETRIES = 2


EvidenceCategory = Literal[
    "skill",
    "project",
    "experience",
    "achievement",
    "education",
    "certification",
    "responsibility",
    "other",
]


class ExtractedMetric(BaseModel):
    name: str
    value: str
    context: str | None = None


class ExtractedFact(BaseModel):
    claim: str = Field(
        min_length=3,
        description=(
            "Atomic factual claim supported by the source chunk."
        ),
    )
    category: EvidenceCategory
    skills: list[str] = Field(
        default_factory=list
    )
    metrics: list[
        ExtractedMetric
    ] = Field(default_factory=list)

    @field_validator(
        "metrics",
        mode="before",
    )
    @classmethod
    def discard_incomplete_metrics(
        cls,
        metrics,
    ):
        if metrics is None:
            return []

        if not isinstance(
            metrics,
            list,
        ):
            return metrics

        cleaned = []

        for metric in metrics:
            if not isinstance(
                metric,
                dict,
            ):
                cleaned.append(metric)
                continue

            name = metric.get("name")
            value = metric.get("value")

            if name is None or value is None:
                continue

            if (
                isinstance(name, str)
                and not name.strip()
            ):
                continue

            if (
                isinstance(value, str)
                and not value.strip()
            ):
                continue

            cleaned.append(metric)

        return cleaned


class ExtractionResponse(BaseModel):
    evidence: list[
        ExtractedFact
    ] = Field(default_factory=list)


class EvidenceCard(BaseModel):
    evidence_id: str

    claim: str
    category: EvidenceCategory
    skills: list[str]
    metrics: list[ExtractedMetric]

    # Semantic ownership. These are copied from the source chunk and are never
    # generated by the LLM.
    entity_id: str | None = None
    entity_type: str | None = None

    # Provenance
    source_chunk_id: str
    document_id: str
    source_file: str
    source_type: str
    page: int | None = None


SYSTEM_PROMPT = """
You are the evidence extraction component of ResumeForge.

Your job is to extract career-relevant factual evidence from a source chunk.

STRICT RULES:

1. Extract ONLY information explicitly supported by the source text.
2. Never invent technologies, numbers, responsibilities, outcomes, job titles,
   dates, skills, or accomplishments.
3. Do not improve or rewrite achievements to sound more impressive.
4. Do not make assumptions based on what would normally be true.
5. Each evidence item must contain ONE atomic claim.
6. Preserve numerical values exactly as they appear in the source.
7. Skills must be supported by the source text.
8. If the source contains no useful career evidence, return an empty list.
9. Do not extract vague filler statements.
10. Return valid JSON only.
11. Extract at most 8 high-value evidence items from each chunk.
12. Prefer concrete resume-relevant evidence over trivial biographical facts.
13. Do not infer current status.
14. The JSON example describes structure only. Never copy example facts.
15. A metric may be included ONLY when its exact value is explicitly present.
16. Do not strengthen skill wording beyond what the source supports.
17. Metrics are optional. If no explicit metric exists, use "metrics": [].
18. Never return null or empty strings for a metric name or value.
19. Skills, technologies, job titles, and descriptive text are not metrics.
20. Entity ownership is provided by the system. Do not invent or change it.

Required output format:

{
  "evidence": [
    {
      "claim": "<atomic factual claim from source>",
      "category": "project",
      "skills": ["<explicitly supported skill>"],
      "metrics": [
        {
          "name": "<metric name>",
          "value": "<exact metric value>",
          "context": "<optional context>"
        }
      ]
    }
  ]
}

Allowed category values:
skill
project
experience
achievement
education
certification
responsibility
other
""".strip()


def build_user_prompt(
    chunk: dict,
) -> str:
    return f"""
Extract resume-relevant evidence from the following source chunk.

ENTITY ID:
{chunk.get("entity_id")}

ENTITY TYPE:
{chunk.get("entity_type")}

SOURCE TYPE:
{chunk["source_type"]}

SOURCE FILE:
{chunk["source_file"]}

PAGE:
{chunk.get("page")}

SOURCE TEXT:
--- BEGIN SOURCE ---
{chunk["text"]}
--- END SOURCE ---

Return JSON only.
""".strip()


def load_jsonl(
    path: Path,
) -> list[dict]:
    if not path.exists():
        return []

    records: list[dict] = []

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:
        for line in file:
            line = line.strip()

            if line:
                records.append(
                    json.loads(line)
                )

    return records


def save_jsonl_atomic(
    path: Path,
    records: list[dict],
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, temp_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temp_path = Path(temp_name)

    try:
        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
        ) as file:
            for record in records:
                json.dump(
                    record,
                    file,
                    ensure_ascii=False,
                )
                file.write("\n")

            file.flush()
            os.fsync(file.fileno())

        os.replace(temp_path, path)

    except Exception:
        temp_path.unlink(
            missing_ok=True
        )
        raise


def empty_state() -> dict:
    return {
        "version": STATE_VERSION,
        "chunks": {},
    }


def load_state(
    path: Path,
) -> dict:
    if not path.exists():
        return empty_state()

    try:
        with path.open(
            "r",
            encoding="utf-8",
        ) as file:
            state = json.load(file)

    except (
        json.JSONDecodeError,
        OSError,
    ):
        return empty_state()

    if not isinstance(state, dict):
        return empty_state()

    if state.get("version") != STATE_VERSION:
        return empty_state()

    if not isinstance(
        state.get("chunks"),
        dict,
    ):
        return empty_state()

    return state


def save_state_atomic(
    path: Path,
    state: dict,
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fd, temp_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temp_path = Path(temp_name)

    try:
        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                state,
                file,
                indent=2,
                ensure_ascii=False,
            )
            file.flush()
            os.fsync(file.fileno())

        os.replace(temp_path, path)

    except Exception:
        temp_path.unlink(
            missing_ok=True
        )
        raise


def get_model_revision(
    llm: LLM,
) -> str | None:
    model = getattr(
        llm,
        "model",
        None,
    )
    config = getattr(
        model,
        "config",
        None,
    )

    return getattr(
        config,
        "_commit_hash",
        None,
    )


def make_extraction_hash(
    chunk: dict,
    llm: LLM,
) -> str:
    payload = {
        "chunk_id": chunk["chunk_id"],
        "document_id": (
            chunk["document_id"]
        ),
        "source_file": (
            chunk["source_file"]
        ),
        "source_type": (
            chunk["source_type"]
        ),
        "page": chunk.get("page"),
        "entity_id": chunk.get(
            "entity_id"
        ),
        "entity_type": chunk.get(
            "entity_type"
        ),
        "text": chunk["text"],
        "model_name": llm.name,
        "backend": type(llm).__name__,
        "model_revision": (
            get_model_revision(llm)
        ),
        "system_prompt": SYSTEM_PROMPT,
        "user_prompt": (
            build_user_prompt(chunk)
        ),
        "generation": {
            "max_new_tokens": (
                EXTRACTION_MAX_NEW_TOKENS
            ),
            "temperature": (
                EXTRACTION_TEMPERATURE
            ),
            "top_p": EXTRACTION_TOP_P,
            "retries": EXTRACTION_RETRIES,
        },
        "schema": (
            ExtractionResponse
            .model_json_schema()
        ),
    }

    serialized = json.dumps(
        payload,
        sort_keys=True,
        ensure_ascii=False,
    )

    return hashlib.sha256(
        serialized.encode("utf-8")
    ).hexdigest()


def make_evidence_id(
    chunk_id: str,
    claim: str,
) -> str:
    raw = (
        f"{chunk_id}:"
        f"{claim.strip().lower()}"
    )

    digest = hashlib.sha256(
        raw.encode("utf-8")
    ).hexdigest()

    return f"ev_{digest[:16]}"


def deduplicate_strings(
    values: list[str],
) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []

    for value in values:
        cleaned = value.strip()

        if not cleaned:
            continue

        key = cleaned.casefold()

        if key in seen:
            continue

        seen.add(key)
        result.append(cleaned)

    return result


def extract_json_object(
    raw: str,
) -> dict:
    text = raw.strip()

    if text.startswith("```"):
        lines = text.splitlines()

        if lines:
            lines = lines[1:]

        if (
            lines
            and lines[-1].strip()
            == "```"
        ):
            lines = lines[:-1]

        text = "\n".join(
            lines
        ).strip()

    try:
        return json.loads(text)

    except json.JSONDecodeError:
        pass

    start = text.find("{")
    end = text.rfind("}")

    if (
        start == -1
        or end == -1
        or end <= start
    ):
        raise ValueError(
            "Model output did not contain a JSON object."
        )

    return json.loads(
        text[start:end + 1]
    )


def _repair_prompt(
    error: Exception,
) -> str:
    if isinstance(
        error,
        ValidationError,
    ):
        return (
            "Your previous response is valid JSON, but it does not match "
            "the required extraction schema.\n\n"
            f"Schema validation error:\n{error}\n\n"
            "Repair only schema/type problems.\n"
            "Do not invent or add factual information.\n"
            "Do not invent replacement metric values.\n"
            "Every metric must have a non-empty string name and value.\n"
            "If a metric has a null, missing, or empty name/value, remove "
            "that metric object.\n"
            "If an evidence item has no valid metrics, use \"metrics\": [].\n"
            "Return the complete corrected JSON object only."
        )

    return (
        "Your previous response is not valid JSON.\n\n"
        f"Parsing error:\n{error}\n\n"
        "Repair only the JSON syntax.\n"
        "Do not add, remove, rewrite, or reinterpret factual claims.\n"
        "Return the complete corrected JSON object only."
    )


def extract_facts(
    llm: LLM,
    chunk: dict,
    retries: int = EXTRACTION_RETRIES,
) -> list[ExtractedFact]:
    messages: list[dict] = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": (
                build_user_prompt(chunk)
            ),
        },
    ]

    config = GenConfig(
        max_new_tokens=(
            EXTRACTION_MAX_NEW_TOKENS
        ),
        temperature=(
            EXTRACTION_TEMPERATURE
        ),
        top_p=EXTRACTION_TOP_P,
    )

    last_error: Exception | None = None

    for attempt in range(
        retries + 1
    ):
        raw_response = llm.generate(
            messages,
            config=config,
        )

        try:
            parsed_json = (
                extract_json_object(
                    raw_response
                )
            )

            response = (
                ExtractionResponse
                .model_validate(
                    parsed_json
                )
            )

            return response.evidence

        except (
            json.JSONDecodeError,
            ValidationError,
            ValueError,
        ) as error:
            last_error = error

            print(
                f"  Invalid model output "
                f"(attempt "
                f"{attempt + 1}/"
                f"{retries + 1}): "
                f"{error}"
            )

            if attempt >= retries:
                break

            messages.extend(
                [
                    {
                        "role": "assistant",
                        "content": raw_response,
                    },
                    {
                        "role": "user",
                        "content": (
                            _repair_prompt(error)
                        ),
                    },
                ]
            )

    raise RuntimeError(
        "Could not extract valid evidence: "
        f"{last_error}"
    )


def build_evidence_cards(
    chunk: dict,
    facts: list[ExtractedFact],
) -> list[EvidenceCard]:
    cards: list[EvidenceCard] = []

    for fact in facts:
        claim = fact.claim.strip()
        skills = deduplicate_strings(
            fact.skills
        )

        cards.append(
            EvidenceCard(
                evidence_id=(
                    make_evidence_id(
                        chunk["chunk_id"],
                        claim,
                    )
                ),
                claim=claim,
                category=fact.category,
                skills=skills,
                metrics=fact.metrics,
                entity_id=chunk.get(
                    "entity_id"
                ),
                entity_type=chunk.get(
                    "entity_type"
                ),
                source_chunk_id=(
                    chunk["chunk_id"]
                ),
                document_id=(
                    chunk["document_id"]
                ),
                source_file=(
                    chunk["source_file"]
                ),
                source_type=(
                    chunk["source_type"]
                ),
                page=chunk.get("page"),
            )
        )

    return cards


def evidence_ids_for_records(
    records: list[dict],
) -> list[str]:
    return sorted(
        record["evidence_id"]
        for record in records
        if "evidence_id" in record
    )


def cache_entry_is_valid(
    *,
    evidence_cache_exists: bool,
    old_chunk_state: dict | None,
    current_fingerprint: str,
    old_cards: list[dict],
) -> bool:
    if not evidence_cache_exists:
        return False

    if not old_chunk_state:
        return False

    if (
        old_chunk_state.get(
            "fingerprint"
        )
        != current_fingerprint
    ):
        return False

    expected_ids = sorted(
        old_chunk_state.get(
            "evidence_ids",
            [],
        )
    )
    actual_ids = (
        evidence_ids_for_records(
            old_cards
        )
    )

    return expected_ids == actual_ids


def extract_corpus(
    llm: LLM,
    chunks_file: Path = CHUNKS_FILE,
    evidence_file: Path = EVIDENCE_FILE,
    state_file: Path = STATE_FILE,
) -> None:
    chunks = load_jsonl(
        chunks_file
    )

    if not chunks:
        raise RuntimeError(
            f"No chunks found in {chunks_file}. "
            "Evidence extraction cannot continue."
        )

    old_state = load_state(
        state_file
    )
    old_evidence = load_jsonl(
        evidence_file
    )

    old_by_chunk: dict[
        str,
        list[dict],
    ] = {}

    for card in old_evidence:
        old_by_chunk.setdefault(
            card.get(
                "source_chunk_id",
                "",
            ),
            [],
        ).append(card)

    new_state = empty_state()
    new_records: list[dict] = []

    processed = 0
    skipped = 0
    failed = 0

    print()
    print(
        "ResumeForge Evidence Extractor"
    )
    print(
        "------------------------------"
    )
    print(
        f"Chunks discovered: {len(chunks)}"
    )
    print()

    evidence_cache_exists = (
        evidence_file.exists()
    )

    for index, chunk in enumerate(
        chunks,
        start=1,
    ):
        chunk_id = chunk[
            "chunk_id"
        ]
        fingerprint = (
            make_extraction_hash(
                chunk,
                llm,
            )
        )
        old_chunk_state = (
            old_state[
                "chunks"
            ].get(chunk_id)
        )
        old_cards = old_by_chunk.get(
            chunk_id,
            [],
        )

        if cache_entry_is_valid(
            evidence_cache_exists=(
                evidence_cache_exists
            ),
            old_chunk_state=(
                old_chunk_state
            ),
            current_fingerprint=(
                fingerprint
            ),
            old_cards=old_cards,
        ):
            print(
                f"[{index}/{len(chunks)}] "
                f"SKIP {chunk_id}"
            )

            new_records.extend(
                old_cards
            )
            new_state["chunks"][
                chunk_id
            ] = old_chunk_state
            skipped += 1
            continue

        print(
            f"[{index}/{len(chunks)}] "
            f"EXTRACT {chunk_id}"
        )

        try:
            facts = extract_facts(
                llm,
                chunk,
            )
            cards = (
                build_evidence_cards(
                    chunk,
                    facts,
                )
            )

        except Exception as error:
            failed += 1
            print(
                f"  FAILED: {error}"
            )
            raise RuntimeError(
                "Evidence extraction failed for chunk "
                f"{chunk_id}. Aborting to prevent stale evidence "
                "from being treated as current."
            ) from error

        serialized_cards = [
            card.model_dump()
            for card in cards
        ]

        new_records.extend(
            serialized_cards
        )
        new_state["chunks"][
            chunk_id
        ] = {
            "fingerprint": (
                fingerprint
            ),
            "evidence_ids": [
                card.evidence_id
                for card in cards
            ],
        }

        processed += 1

        print(
            f"  -> {len(cards)} "
            "evidence cards"
        )

    save_jsonl_atomic(
        evidence_file,
        new_records,
    )
    save_state_atomic(
        state_file,
        new_state,
    )

    print()
    print("Extraction complete")
    print("-------------------")
    print(
        f"New/changed processed: {processed}"
    )
    print(
        f"Unchanged skipped:     {skipped}"
    )
    print(
        f"Failed:                {failed}"
    )
    print(
        f"Evidence cards:        {len(new_records)}"
    )
    print(
        f"Output:                {evidence_file}"
    )
    print(
        f"State:                 {state_file}"
    )
